Add "--noconfig" to the ant call. Forrest uses our own packaged ant, so we don't want to use system config. Suggested by: Richard Calmbach Issue: FOR-471 Missing "--noconfig" causes NoClassDefFoundError due to ant sourcing external config files
git-svn-id: https://svn.apache.org/repos/asf/forrest/trunk@158412 13f79535-47bb-0310-9956-ffa450edef68